### ISSUE TITLE
Difference with esbuild’s native `define` option?

### ISSUE THREAD

**Issue by laurentpayot** [naecoo/esbuild-plugin-replace#4]
Hi, can you tell why people should use this plugin instead of esbuild’s native [`define` option](https://esbuild.github.io/api/#define)?

Cheers

**Comment by naecoo** [comment]
Esbuild's native define API not support [include](https://github.com/naecoo/esbuild-plugin-replace#include) option, that's the only difference. If you don't have this requirement, I would recommend you to use the native API.

**Comment by gunters63** [comment]
Esbuild can not replace arbitrary strings it seems, esbuild-plugin-replace can, if you set the delimiters to ['', '']
