### ISSUE TITLE
Regex pattern not match in some case

### ISSUE THREAD

**Issue by issazhu** [naecoo/esbuild-plugin-replace#5]
As I was using typescript for my project, and I would like to setup the alias when I import file from root path.  When my alias path is '@/src/......', pattern will fail to match in this case.  
`  const pattern = new RegExp(`\\b(${keys.join('|')})\\b`, 'g');`
 \b may cause something wrong in this case.

// to reproduce
`
plugins: [
    replace({'@/src/':'./'}),
  ],
`

**Comment by naecoo** [comment]
I released a new version 1.2.0, adds a new [delimiters](https://github.com/naecoo/esbuild-plugin-replace#delimiters) option. You can set it to `['', '']` to solve your problem.
