### ISSUE TITLE
过滤上遇到了问题，求助

### ISSUE THREAD

**Issue by takegine** [naecoo/esbuild-plugin-replace#9]
大佬你好，我在传参上遇到了一些问题，希望您能帮助我
主要是`lodash.js`中的一句 eval我这里不允许执行，需要替换掉
···
    {
            "Function('return this')": "(() => globalThis)"
    }
···
我直接这样传参，编译时得到了一个报错
···
X [ERROR] [plugin replace] ENOENT: no such file or directory, open 'E:\gitee\itemName\node_modules\.pnpm\object-inspect@1.12.3\node_modules\object-inspect\util.inspect'

    node_modules/.pnpm/object-inspect@1.12.3/node_modules/object-inspect/index.js:68:26:
      68 │ var utilInspect = require('./util.inspect');
         ╵                           ~~~~~~~~~~~~~~~~

1 error

     .....

  errors: [
    {
      detail: [Error],
      id: '',
      location: [Object],
      notes: [],
      pluginName: 'replace',
      text: "ENOENT: no such file or directory, open 'E:\\gitee\\itemName\\node_modules\\.pnpm\\object-inspect@1.12.3\\node_modules\\object-inspect\\util.inspect'"
    }
  ],
  warnings: []
}
···

我尝试换成 
```
  {
      include:/lodash.js/,
      values:{
            "Function('return this')": "(() => globalThis)",
            'Function("return this")': "(() => globalThis)"
      }
  }
```
但是输出的文件中 ` var root = freeGlobal || freeSelf || Function("return this")();` 并没有被替换。
我也试过 `include: /.*\/lodash.js/` 和 `exclude:/object-inspect/,` 但貌似也没有生效

我该如何做，才能改掉这一句？

**Comment by naecoo** [comment]
参考以下代码：
```javascript
build({
  plugins: [
    replace({
      include: /node_modules\/lodash\/cloneDeep/,
      delimiters: ['', ''],
      values: {
        "Function('remturn this')": `(() => globalThis)`
      }
    })
  ]
})
```

不过你的需求我建议用这个 [patch-package](https://www.npmjs.com/package/patch-package) 工具来实现。
